name: Build UpSkope (Release Win32/AnyCPU)

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild (VS2022)
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\NuGet\Cache
            ~\AppData\Local\NuGet\v3-cache
            ~\.nuget\packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config', '**/*.csproj', '**/*.sln') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore NuGet (solution)
        shell: pwsh
        run: nuget restore .\UpSkope.sln

      # Evite les cibles qui comparent $(MsBuildMajorVersion) quand elle est vide
      - name: Guard MsBuildMajorVersion
        shell: pwsh
        run: |
          @'
          <Project>
            <PropertyGroup>
              <MsBuildMajorVersion Condition="'$(MsBuildMajorVersion)' == ''">17</MsBuildMajorVersion>
            </PropertyGroup>
          </Project>
          '@ | Set-Content -Path Directory.Build.props -Encoding UTF8

      # Build C# (Any CPU) - Release
      - name: Build UpSkope (C# AnyCPU)
        shell: pwsh
        run: |
          msbuild .\UpSkope\UpSkope.csproj /m `
            /p:Configuration=Release `
            /p:Platform="Any CPU" `
            /p:MsBuildMajorVersion=17

      # Build C++ Win32 (Release)
      - name: Build IPCProxy (C++ Win32)
        shell: pwsh
        run: |
          msbuild .\IPCProxy\IPCProxy.vcxproj /m `
            /p:Configuration=Release `
            /p:Platform=Win32 `
            /p:PlatformToolset=v143 `
            /p:MsBuildMajorVersion=17

      - name: Build CustomAction (C++ Win32)
        shell: pwsh
        run: |
          msbuild .\CustomAction\CustomAction.vcxproj /m `
            /p:Configuration=Release `
            /p:Platform=Win32 `
            /p:PlatformToolset=v143 `
            /p:MsBuildMajorVersion=17

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UpSkope-Release-Win32
          path: |
            UpSkope\bin\Release\**\UpSkope.exe
            IPCProxy\Win32\Release\**\*.dll
            CustomAction\Win32\Release\**\*.dll
          if-no-files-found: warn
