name: Build UpSkope

# <-- AJOUT : droits pour publier une Release
permissions:
  contents: write

on:
  push:
    branches: ["**"]
    tags: ["v*"]           # ex: v1.0.0
  pull_request:
  # (optionnel) déclencheur manuel pour publier sans pousser un tag local
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag à publier (ex: v1.0.0)"
        required: false

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Cache NuGet
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Local\NuGet\Cache
          ~\AppData\Local\NuGet\v3-cache
          ~\.nuget\packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config', '**/*.csproj', '**/*.sln') }}
        restore-keys: nuget-${{ runner.os }}-

    - name: Restore Nu
