name: Build UpSkope (.NET + C++)

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild (VS2022)
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\NuGet\Cache
            ~\AppData\Local\NuGet\v3-cache
            ~\.nuget\packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config', '**/*.csproj', '**/*.sln') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore NuGet (solution)
        shell: pwsh
        run: nuget restore .\UpSkope.sln

      # Empêche l’interprétation PowerShell dans le props + évite les targets qui comparent MsBuildMajorVersion vide
      - name: Guard MsBuildMajorVersion
        shell: pwsh
        run: |
          @'
          <Project>
            <PropertyGroup>
              <MsBuildMajorVersion Condition="'$(MsBuildMajorVersion)' == ''">17</MsBuildMajorVersion>
            </PropertyGroup>
          </Project>
          '@ | Set-Content -Path Directory.Build.props -Encoding UTF8

      # Build C# (souvent Any CPU)
      - name: Build UpSkope (C#)
        shell: pwsh
        run: |
          msbuild .\UpSkope\UpSkope.csproj /m `
            /p:Configuration=Release `
            /p:Platform="Any CPU" `
            /p:MsBuildMajorVersion=17

      # Build C++ (x64). Si ton repo est en Win32, remplace Platform=x64 par Platform=Win32
      - name: Build IPCProxy (C++)
        shell: pwsh
        run: |
          msbuild .\IPCProxy\IPCProxy.vcxproj /m `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:PlatformToolset=v143 `
            /p:MsBuildMajorVersion=17

      - name: Build CustomAction (C++)
        shell: pwsh
        run: |
          msbuild .\CustomAction\CustomAction.vcxproj /m `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:PlatformToolset=v143 `
            /p:MsBuildMajorVersion=17

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UpSkope-Release
          path: |
            UpSkope\bin\Release\**\UpSkope.exe
            IPCProxy\x64\Release\**\*.dll
            CustomAction\x64\Release\**\*.dll
          if-no-files-found: warn
