name: Build UpSkope (.NET + C++)

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    env:
      Solution_Name: UpSkope.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # .NET SDK (utile pour les outils dotnet si besoin ; le projet C# est .NET Framework,
      # mais avoir dotnet CLI dispo ne gêne pas)
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Ajoute MSBuild 17 (VS2022) au PATH
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Cache NuGet
      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\NuGet\Cache
            ~\AppData\Local\NuGet\v3-cache
            ~\.nuget\packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config', '**/*.csproj', '**/*.sln') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # Restore NuGet (solution)
      - name: Restore NuGet
        shell: pwsh
        run: nuget restore "$env:Solution_Name"

      # Évite les erreurs de comparaison numérique si MsBuildMajorVersion est vide dans certains targets
      - name: Guard MsBuildMajorVersion
        shell: pwsh
        run: |
          @'
          <Project>
            <PropertyGroup>
              <MsBuildMajorVersion Condition="'$(MsBuildMajorVersion)' == ''">17</MsBuildMajorVersion>
            </PropertyGroup>
          </Project>
          '@ | Set-Content -Path Directory.Build.props -Encoding UTF8

      # Build C# (.NET Framework) + C++ (v143) en Release/x64
      - name: Build solution
        shell: pwsh
        run: |
          msbuild "$env:Solution_Name" /m `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=${{ matrix.platform }} `
            /p:PlatformToolset=v143 `
            /p:MsBuildMajorVersion=17

      # Publie les binaires utiles (EXE/DLL). Adapter si dossiers différents.
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UpSkope-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            UpSkope\bin\${{ matrix.configuration }}\**\UpSkope.exe
            IPCProxy\${{ matrix.platform }}\${{ matrix.configuration }}\**\*.dll
            CustomAction\${{ matrix.platform }}\${{ matrix.configuration }}\**\*.dll
          if-no-files-found: warn
